/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NewTodoDialog: typeof import('./src/components/NewTodoDialog.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
